### ISSUE TITLE
Crash on load due to loading a sound file

### ISSUE THREAD

**Issue by emmaloool** [twrabetz/CGP-Final-YogurtCoffee#13]
[](url
<img width="917" alt="Screen Shot 2021-11-30 at 10 52 04 AM" src="https://user-images.githubusercontent.com/33307632/144081071-faa1caad-4751-4d4f-a1b9-bbc99aee1369.png">
)

**Comment by Whotakesmyname** [comment]
Converted that wav to opus. This should fix it. Thank you for reporting!
