### ISSUE TITLE
Game is too dark. I can barely see anything on my monitor

### ISSUE THREAD

**Issue by gcwhitfield** [twrabetz/CGP-Final-YogurtCoffee#7]
MacOS 10.14.6
Processor: 2.8 GHz Intel Core i7
Memory: 16 GB 2133 MHz LPDDR3
GPU: Intel HD Graphics 630 1536 MB

<img width="1680" alt="スクリーンショット 2021-11-30 午前10 24 32" src="https://user-images.githubusercontent.com/29950517/144076948-cb107d33-843a-4e49-9ca7-bb50df07c205.png">

**Comment by annehe9** [comment]
Bump, I had to max out my screen brightness to see anything.

**Comment by mwmccoy** [comment]
Same here, but I can't even see the lights on the windows build, so the screen is almost entirely black.

**Comment by Whotakesmyname** [comment]
It is a little strange that the result of a set of cross-platform APIs can differ on different PC. But whatever, we increased the ambient light in the scene. Hope it works for you now.
